### ISSUE TITLE
pip install fails if pathlib not installed

### ISSUE THREAD

**Issue by roscisz** [roscisz/TensorHive#101]
Is it OK that we use pathlib in setup.py?

  Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-31ahc6/setup.py", line 58, in <module>
        copy_configuration_files()
      File "/tmp/pip-req-build-31ahc6/setup.py", line 7, in copy_configuration_files
        from pathlib import PosixPath
    ImportError: No module named pathlib

**Comment by roscisz** [comment]
After installing pathlib:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-HlD2uX/setup.py", line 58, in <module>
        copy_configuration_files()
      File "/tmp/pip-req-build-HlD2uX/setup.py", line 8, in copy_configuration_files
        target_dir = PosixPath.home() / '.config/TensorHive'
    AttributeError: type object 'PosixPath' has no attribute 'home'

**Comment by roscisz** [comment]
With pip3 everything works fine

**Comment by micmarty** [comment]
Do you remember that we do not support python 2? There are no problems with `pathlib` in `setup.py` because it's python 3 built-in.
