### ISSUE TITLE
tensorhive binary doesn't work with virtualenv

### ISSUE THREAD

**Issue by roscisz** [roscisz/TensorHive#132]
Doesn't seem to work with virtualenv:

```
virtualenv --python=/usr/bin/python3 venv/
source venv/bin/activate
pip install .
tensorhive -l info

Traceback (most recent call last):
  File "/usr/local/bin/tensorhive", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tensorhive' distribution was not found and is required by the application

```

"python -m tensorhive" works

**Comment by micmarty** [comment]
stale, not relevant
