### ISSUE TITLE
Mailbot: notify_intruder=no is not respected + critical exception is raised

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#164]
After db migration, all email addresses were set to `None` by default, but Sqlalchemy was told to replace these `None` values with `<email_missing>` (`default_server`).

Even if intruder notifications are off, TH tries to fetch email addresses from the database and what's worse it treats `<email_missing>` as correct data, resulting in following exception:

### Log captured by @roscisz 
```
CRITICAL | 2019-03-12 16:06:57 | ProtectionService_Thread-2     | MSG: {'<email_missing>': (553, b'5.1.2 The recipient address <email_missing> is not a valid RFC-5321 address. u29sm1365182ljd.84 - gsmtp')} | FROM: tensorhive.core.violation_handlers.EmailSendingBehaviour
Traceback (most recent call last):
  File "/home/tensorhive/TensorHive/tensorhive/core/violation_handlers/EmailSendingBehaviour.py", line 136, in trigger_action
    self.send_email_to_intruder(violation_data)
  File "/home/tensorhive/TensorHive/tensorhive/core/violation_handlers/EmailSendingBehaviour.py", line 95, in send_email_to_intruder
    self.mailer.send(email)
  File "/home/tensorhive/TensorHive/tensorhive/core/utils/mailer.py", line 80, in send
    self.server.sendmail(message.author, message.recipients, message.body)
  File "/usr/lib/python3.5/smtplib.py", line 876, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'<email_missing>': (553, b'5.1.2 The recipient address <email_missing> is not a valid RFC-5321 address. u29sm1365182ljd.84 - gsmtp')}
```

**Comment by roscisz** [comment]
fixed in #168
