### ISSUE TITLE
Tensorhive behind reverse proxy

### ISSUE THREAD

**Issue by Dubrzr** [roscisz/TensorHive#286]
Dzień dobry!

### Subject of the issue

I'm currently trying to run your application in our environment (~80 gpus) but when I try to use it behind a reverse proxy (like nginx/apache) which is a standard way of exposing a webapp, I don't find any way to specify that the gevent api should be called on the same url, or on another url than the gunicorn server.

More precisely: 

url of gunicorn = https://something.com/  

When a user access it here is the process:

```
https://something.com/ --https:443--> nginx (for ssl termination) --http:5000--> gunicorn
```

When accessing https://something.com/, I'm trying to connect using admin account but the front-end calls http://something.com:1111/api/0.3.1/user/login : this is not a standard way to call this gevent api, as it is using port 1111, and this is not authorized in our environment.

How can I make the front-end to call the gevent api in either of those possibilities? :

1. On the same url than gunicorn, but maybe with a prefix like "/api": https://something.com/api/
2. On a different url, like https://something-api.com/

### Steps to reproduce

My main_config.ini looks like this:

```
...

[api]
title = TensorHive API
version = 0.3.1
url_hostname = something.com
url_prefix = api/%(version)s
spec_file = api_specification.yml
impl_location = tensorhive.api.controllers

[web_app.server]
backend = gunicorn
host = 0.0.0.0
port = 5000
loglevel = warning
workers = 8

[api.server]
backend = gevent
host = 0.0.0.0
port = 1111
debug = off

...

```

Thanks for this project that looks very promising!

**Comment by roscisz** [comment]
@Dubrzr Dzień dobry! And thank you for trying out TensorHive.

I took the chance to reproduce an environment similar to yours, and I was able to serve TH through a nginx reverse proxy in both suggested scenarios, as well as a third one:

1. the same URL with /api suffix
2. different hostname
3. the same hostname, different port

Since TH indeed needs two HTTP endpoints (one for the Web application, second for API), two nginx locations are required.
The difference between these scenarios is only in nginx configuration -- for 1, a single nginx site ("server" configuration entry) with two locations is required, while in scenarios 2 and 3, two sites are required with one location each. I will describe scenario 1, because I find it the most elegant, but translating this to scenarios 2 and 3 should be straightforward.

/etc/nginx/sites-enabled/tensorhive:

```
server {

	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;

	include snippets/snakeoil.conf;

	server_name tensorhive;

	location / {
		proxy_pass <internal server hostname or IP>:5000;
	}

	location /api {
		proxy_pass <internal server hostname or IP>:1111;
	}
}
```

If the 1111 port is blocked in your local network, you can change the port in ~/.config/TensorHive/main_config.ini in section [api.server], variable "port", and adjust the nginx configuration accordingly.

Unfortunately, currently TH cannot be easily configured to bind one URL for API and use another URL in webapp. I created issue #288 to fix it. However, in the meantime there is an easy workaround - find the app/web/AppServer.py file in your TH installation (for example /usr/local/lib/python3.6/site-packages/tensorhive/app/web/AppServer.py), and modify lines 52-59 as follows:

```
data = {
            'apiPath': 'https://{}:{}/{}'.format(
                '<external server hostname or IP>',
                <external HTTP port>,
                API.URL_PREFIX),
            'version': tensorhive.__version__,
            'apiVersion': API.VERSION
        }
```

**Comment by Dubrzr** [comment]
Dzień dobry! 😃

I just tested, I can confirm the workaround n°1 works fine (having the same URL with /api suffix)! Thank you!
We also use this approach for other internal frontend+api web apps.

I've got an error in logs : 

```
août 31 16:00:54 bbs-edsnas-p001.bbs.aphp.fr bash[32655]: ERROR    | 2020-08-31 16:00:54 | MonitoringService_Thread-1     | MSG: cpu query raised AssertionError on host.number.two                  | FROM: tensorhive.core.monitors.CPUMonitor
```

Is it supposed to detect multiple GPUs on the machines ? I've added three of them in hosts_config.ini, tensorhive test works fine : 

```
bash-4.2$ tensorhive test
[⚙] Testing SSH connections using key: ~/.config/TensorHive/ssh_key
[✔] gpu1.***.com OK
[✔] gpu2.***.com OK
[✔] gpu3.***.com OK
```

Here I can only see machines, but not machine's gpus (each machine has 8*P40 nvidia) 💯 

![image](https://user-images.githubusercontent.com/3718838/91735812-20c6f200-ebad-11ea-9db1-dc80907fceb7.png)

I can run nvidia-smi:

```
which nvidia-smi
/usr/bin/nvidia-smi
```

**Comment by roscisz** [comment]
I'm glad it works!

Regarding the GPUs: yes, it should detect the multiple GPUs. They should be visible in the calendar after expanding the node (the blue plus icon):

![obraz](https://user-images.githubusercontent.com/766386/91747881-4c52d800-ebbf-11ea-9e9a-ab8ef8f0c39f.png)

as well as in the `Nodes overview` panel.

It looks like some error in CPU monitor breaks the monitoring service. Can you paste full stack trace of the raised AssertionError?

Also, could you paste the output of `free -m` on one of the monitored nodes? The error might be related to a88c9ab82437931ea657bd560b66d079836d0155, maybe my locale fix wasn't good enough for your version of `free`.

**Comment by Dubrzr** [comment]
Hmmm I cannot see GPUs even when I click on the "+" sign, nothing happens, I guess the http request used is "/api/0.3.1/nodes/metrics" ? If so here are the contents of the response:

```
{
  "gpu1.***.com": {
    "CPU": {
      "CPU_gpu1.***.com": {
        "index": 0,
        "metrics": {
          "mem_free": {
            "unit": "MiB",
            "value": 1295
          },
          "mem_total": {
            "unit": "MiB",
            "value": 192925
          },
          "mem_used": {
            "unit": "MiB",
            "value": 152775
          },
          "utilization": {
            "unit": "%",
            "value": 6.15449
          }
        }
      }
    }
  },
  "gpu2.***.com": {
    "CPU": null
  },
  "gpu3.***.com": {
    "CPU": {
      "CPU_gpu3.***.com": {
        "index": 0,
        "metrics": {
          "mem_free": {
            "unit": "MiB",
            "value": 1039
          },
          "mem_total": {
            "unit": "MiB",
            "value": 192925
          },
          "mem_used": {
            "unit": "MiB",
            "value": 40694
          },
          "utilization": {
            "unit": "%",
            "value": 1.45833
          }
        }
      }
    }
  }
}

```

I replaced all hostnames with fakes ones.

Here are `free -m` results on all my machines: (OS are Centos 7):

```
[root@gpu1 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:         192925      166473        7244        5040       19207       19968
Swap:         15931       14994         937
[root@gpu2 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:         192925      158857        1487        6334       32579       26228
Swap:         15931        7748        8183
[root@gpu3 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:         192925       40692        1036       28797      151196      122702
Swap:         15931           0       15931
```

Also `nvidia-smi`:

```
[root@gpu1 ~]# nvidia-smi
Tue Sep  1 14:23:26 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:14:00.0 Off |                    0 |
| N/A   28C    P0    49W / 250W |  21956MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:15:00.0 Off |                    0 |
| N/A   36C    P0    49W / 250W |  14135MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 00000000:39:00.0 Off |                    0 |
| N/A   54C    P0   163W / 250W |  21849MiB / 22919MiB |     90%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 00000000:3A:00.0 Off |                    0 |
| N/A   52C    P0   177W / 250W |  21886MiB / 22919MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P40           Off  | 00000000:88:00.0 Off |                    0 |
| N/A   23C    P8     9W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           Off  | 00000000:89:00.0 Off |                    0 |
| N/A   30C    P0    50W / 250W |  18663MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P40           Off  | 00000000:B1:00.0 Off |                    0 |
| N/A   25C    P8    10W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P40           Off  | 00000000:B2:00.0 Off |                    0 |
| N/A   22C    P8     9W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4301      C   ...er_conda/miniconda/envs/CCR/bin/python3 18787MiB |
|    0     44728      C   ...se180025/.conda/envs/ner_env/bin/python  3157MiB |
|    1     16768      C   ...er_conda/miniconda/envs/CCR/bin/python3 14125MiB |
|    2     39814      C   ...se170020/.conda/envs/GPUtest/bin/python 21837MiB |
|    3      4301      C   ...er_conda/miniconda/envs/CCR/bin/python3   619MiB |
|    3     23651      C   ...se170020/.conda/envs/GPUtest/bin/python 21255MiB |
|    5      4301      C   ...er_conda/miniconda/envs/CCR/bin/python3 18653MiB |
+-----------------------------------------------------------------------------+

```

```
[root@gpu2 ~]# nvidia-smi
Tue Sep  1 14:23:53 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:14:00.0 Off |                    0 |
| N/A   28C    P0    48W / 250W |  21926MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:15:00.0 Off |                    0 |
| N/A   33C    P0    49W / 250W |    306MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 00000000:39:00.0 Off |                    0 |
| N/A   29C    P0    49W / 250W |    306MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 00000000:3A:00.0 Off |                    0 |
| N/A   28C    P0    49W / 250W |    306MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P40           Off  | 00000000:88:00.0 Off |                    0 |
| N/A   33C    P0    48W / 250W |    306MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           Off  | 00000000:89:00.0 Off |                    0 |
| N/A   25C    P0    48W / 250W |    306MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P40           Off  | 00000000:B1:00.0 Off |                    0 |
| N/A   52C    P0   133W / 250W |  21867MiB / 22919MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P40           Off  | 00000000:B2:00.0 Off |                    0 |
| N/A   47C    P0   207W / 250W |  21867MiB / 22919MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      8757      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    0      8763      C   ...i/.conda/envs/pyenv_dotmani/bin/python3 21767MiB |
|    1      8757      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    1      8763      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    2      8757      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    2      8763      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    3      8757      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    3      8763      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    4      8757      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    4      8763      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    5      8757      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    5      8763      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    6      8757      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    6      8763      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    6     27039      C   ...se170020/.conda/envs/GPUtest/bin/python 21559MiB |
|    7      8757      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    7      8763      C   ...i/.conda/envs/pyenv_dotmani/bin/python3   147MiB |
|    7     23491      C   ...se170020/.conda/envs/GPUtest/bin/python 21559MiB |
+-----------------------------------------------------------------------------+

```


```
[root@gpu3 ~]# nvidia-smi
Tue Sep  1 14:24:13 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:14:00.0 Off |                    0 |
| N/A   31C    P0    49W / 250W |  21950MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:15:00.0 Off |                    0 |
| N/A   40C    P0    48W / 250W |  21923MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 00000000:39:00.0 Off |                    0 |
| N/A   34C    P0    49W / 250W |  21923MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 00000000:3A:00.0 Off |                    0 |
| N/A   31C    P0    49W / 250W |   1699MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P40           Off  | 00000000:88:00.0 Off |                    0 |
| N/A   24C    P8     9W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           Off  | 00000000:89:00.0 Off |                    0 |
| N/A   26C    P8     9W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P40           Off  | 00000000:B1:00.0 Off |                    0 |
| N/A   28C    P8     9W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P40           Off  | 00000000:B2:00.0 Off |                    0 |
| N/A   25C    P8     9W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      6714      C   /opt/gpudb/core/bin/gpudb_cluster_cuda       501MiB |
|    0      6716    C+G   /opt/gpudb/core/bin/gpudb_cluster_cuda     21430MiB |
|    1      6718    C+G   /opt/gpudb/core/bin/gpudb_cluster_cuda     21904MiB |
|    2      6720    C+G   /opt/gpudb/core/bin/gpudb_cluster_cuda     21904MiB |
|    3      4062      C   /opt/conda/envs/rapids/bin/python            319MiB |
|    3     28474      C   /opt/conda/envs/rapids/bin/python            377MiB |
|    3     31448      C   /opt/conda/envs/rapids/bin/python            271MiB |
|    3     33893      C   /opt/conda/envs/rapids/bin/python            229MiB |
|    3     47777      C   /opt/conda/envs/rapids/bin/python            399MiB |
+-----------------------------------------------------------------------------+

```

Thanks for your help :)

**Comment by Dubrzr** [comment]
I've switched to debug mode:

```
[web_app.server]
backend = gunicorn
host = 0.0.0.0
port = 5000
loglevel = debug
workers = 8

[api.server]
backend = gevent
host = 0.0.0.0
port = 1111
debug = on
```

But I don't have stackstrace for the AssertionError.

But I have multiple errors like this: 

```
sept. 01 13:29:02 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: [2020-09-01 13:29:02 +0100] [12133] [DEBUG] GET /reservations_overview
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: ERROR    | 2020-09-01 13:29:02 | MainThread                     | MSG: Exception during reset or similar                                               | FROM: sqlalchemy.pool.impl.NullPool
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: Traceback (most recent call last):
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: File "/home/tensorhive-test/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 671, in _finalize_fairy
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: fairy._reset(pool)
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: File "/home/tensorhive-test/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 858, in _reset
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: pool._dialect.do_rollback(self)
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: File "/home/tensorhive-test/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 502, in do_rollback
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: dbapi_connection.rollback()
sept. 01 13:29:03 bbs-edsnas-p001.bbs.aphp.fr bash[23518]: sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140557930149632 and this is thread id 140558353434432.
```

**Comment by roscisz** [comment]
It seems that the reverse proxy issue has been resolved, so for clarity I moved our discussion to a new issue: #289
